# Generated by Django 3.2.8 on 2021-10-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='form',
            field=models.CharField(default='all kinds', max_length=100),
        ),
    ]
