# Generated by Django 3.2.8 on 2021-10-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_film_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(default='Images/Nono/No.img', upload_to='Image/'),
        ),
    ]
